echo off
move archimedes-w.* 1
move 3do-w.* 1
move 3ds-w.* 1
move abuse-w.* 1
move acclaim-w.* 1
move actionmax-w.* 1
move adam-w.* 1
move advision-w.* 1
move alephone-w.* 1
move alg-w.* 1
move alphadenshi-w.* 1
move amcoe-w.* 1
move amiga1200-w.* 1
move amiga500-w.* 1
move amigacd32-w.* 1
move amigacdtv-w.* 1
move amigademo-w.* 1
move amstradcpc-w.* 1
move apfm1000-w.* 1
move apple2-w.* 1
move apple2gs-w.* 1
move arcadia-w.* 1
move arduous-w.* 1
move astrocade-w.* 1
move astrocde-w.* 1
move atari-w.* 1
move atari2600-w.* 1
move atari5200-w.* 1
move atari7800-w.* 1
move atari800-w.* 1
move atarijaguar-w.* 1
move atarijaguarcd-w.* 1
move atarilynx-w.* 1
move atarist-w.* 1
move atlus-w.* 1
move atom-w.* 1
move atomiswave-w.* 1
move avp-w.* 1
move awgl-w.* 1
move banpresto-w.* 1
move bbc-w.* 1
move bbcmicro-w.* 1
move bbja-w.* 1
move bermuda-w.* 1
move bigfish-w.* 1
move bk-w.* 1
move blues-w.* 1
move bstone-w.* 1
move c128-w.* 1
move c20-w.* 1
move c64-w.* 1
move camplynx-w.* 1
move cannonball-w.* 1
move cave-w.* 1
move cave3rd-w.* 1
move cavestory-w.* 1
move cdi-w.* 1
move cdogs-w.* 1
move centurye-w.* 1
move cgenius-w.* 1
move chailove-w.* 1
move channelf-w.* 1
move chihiro-w.* 1
move cinematronics-w.* 1
move coco-w.* 1
move colecovision-w.* 1
move comad-w.* 1
move cplus4-w.* 1
move cps1-w.* 1
move cps2-w.* 1
move cps3-w.* 1
move craft-w.* 1
move creativision-w.* 1
move crvision-w.* 1
move daphne-w.* 1
move dataeast-w.* 1
move devilutionx-w.* 1
move dinothawr-w.* 1
move doom3-w.* 1
move dos-w.* 1
move dreamcast-w.* 1
move droidports-w.* 1
move dynax-w.* 1
move easyrpg-w.* 1
move ecwolf-w.* 1
move eduke32-w.* 1
move eighting-w.* 1
move electron-w.* 1
move ep128emu-w.* 1
move etekwar-w.* 1
move exidy-w.* 1
move f2bgl-w.* 1
move fallout1-w.* 1
move fallout2-w.* 1
move fbneo-w.* 1
move fds-w.* 1
move flash-w.* 1
move flatpak-w.* 1
move fm7-w.* 1
move fmtowns-w.* 1
move fpinball-w.* 1
move freedroid-w.* 1
move gaelco-w.* 1
move gamate-w.* 1
move gameandwatch-w.* 1
move gamecom-w.* 1
move gamecube-w.* 1
move gamegear-w.* 1
move gamepock-w.* 1
move gb-w.* 1
move gb2players-w.* 1
move gba-w.* 1
move gbc-w.* 1
move gbc2players-w.* 1
move gc-w.* 1
move gmaster-w.* 1
move gong-w.* 1
move gottlieb-w.* 1
move gp32-w.* 1
move gx4000-w.* 1
move halflife2-w.* 1
move hcl-w.* 1
move hikaru-w.* 1
move hode-w.* 1
move hurrican-w.* 1
move igs-w.* 1
move ikemen-w.* 1
move imageviewer-w.* 1
move incredibletech-w.* 1
move intellivision-w.* 1
move ionfury-w.* 1
move irem-w.* 1
move j2me-w.* 1
move jaguar-w.* 1
move jaguarcd-w.* 1
move jaleco-w.* 1
move jaxe-w.* 1
move jumpnbump-w.* 1
move kaneko-w.* 1
move kodi-w.* 1
move konami-w.* 1
move laser310-w.* 1
move lcdgames-w.* 1
move library-w.* 1
move lowresnx-w.* 1
move lutro-w.* 1
move lynx-w.* 1
move macintosh-w.* 1
move mame-w.* 1
move mastersystem-w.* 1
move megadrive-w.* 1
move midway-w.* 1
move mitchell-w.* 1
move model2-w.* 1
move model3-w.* 1
move moonlight-w.* 1
move mplayer-w.* 1
move mrboom-w.* 1
move msu-md-w.* 1
move msx1-w.* 1
move msx2-w.* 1
move msx2+-w.* 1
move msxturbor-w.* 1
move mu-w.* 1
move mugen-w.* 1
move multivision-w.* 1
move n64-w.* 1
move n64dd-w.* 1
move namco-w.* 1
move namco2x6-w.* 1
move naomi-w.* 1
move naomi2-w.* 1
move naomi2gd-w.* 1
move naomigd-w.* 1
move nblood-w.* 1
move nds-w.* 1
move neogeo-w.* 1
move neogeocd-w.* 1
move nes-w.* 1
move ngp-w.* 1
move ngpc-w.* 1
move nichibutsu-w.* 1
move nintendo-w.* 1
move nmk-w.* 1
move nukem2-w.* 1
move odcommander-w.* 1
move odyssey2-w.* 1
move omf2097-w.* 1
move openbor-w.* 1
move openclaw-w.* 1
move openjazz-w.* 1
move openjkja-w.* 1
move openjkjo-w.* 1
move openlara-w.* 1
move opentyrian-w.* 1
move pc-w.* 1
move pc88-w.* 1
move pc98-w.* 1
move pce-cd-w.* 1
move pcengine-w.* 1
move pcenginecd-w.* 1
move pcexhumed-w.* 1
move pcfx-w.* 1
move pdp1-w.* 1
move pet-w.* 1
move piboy-w.* 1
move pico-w.* 1
move pico8-w.* 1
move plugnplay-w.* 1
move pokemini-w.* 1
move popcap-w.* 1
move ports-w.* 1
move prboom-w.* 1
move pre2-w.* 1
move prototype-w.* 1
move ps2-w.* 1
move ps3-w.* 1
move psikyo-w.* 1
move psp-w.* 1
move pspmini-w.* 1
move psvita-w.* 1
move psx-w.* 1
move pv1000-w.* 1
move pygame-w.* 1
move pyxel-w.* 1
move quake3-w.* 1
move raptor-w.* 1
move raze-w.* 1
move rednukem-w.* 1
move reminiscence-w.* 1
move rott-w.* 1
move rtcw-w.* 1
move samcoupe-w.* 1
move sameduck-w.* 1
move sammy-w.* 1
move satellaview-w.* 1
move saturn-w.* 1
move scummvm-w.* 1
move scv-w.* 1
move sdlpop-w.* 1
move sega-w.* 1
move sega32x-w.* 1
move segacd-w.* 1
move segastv-w.* 1
move semicom-w.* 1
move serioussam-w.* 1
move seta-w.* 1
move settings-w.* 1
move sg1000-w.* 1
move sg-1000-w.* 1
move sgb-w.* 1
move sm64-w.* 1
move snes-w.* 1
move snes-msu1-w.* 1
move snk-w.* 1
move socrates-w.* 1
move solarus-w.* 1
move sonicretro-w.* 1
move sorr-w.* 1
move spacecadetpinball-w.* 1
move spectravideo-w.* 1
move srb2-w.* 1
move srb2kart-w.* 1
move stalker-w.* 1
move steam-w.* 1
move stk-w.* 1
move stuntcar-w.* 1
move sufami-w.* 1
move superbroswar-w.* 1
move superflappybirds-w.* 1
move supergrafx-w.* 1
move supertux2-w.* 1
move supervision-w.* 1
move supracan-w.* 1
move switch-w.* 1
move taito-w.* 1
move technos-w.* 1
move tecmo-w.* 1
move tg16-w.* 1
move tg-cd-w.* 1
move themehospital-w.* 1
move thextech-w.* 1
move thomson-w.* 1
move ti99-w.* 1
move tic80-w.* 1
move toaplan-w.* 1
move triforce-w.* 1
move tutor-w.* 1
move twentyfourtyeight-w.* 1
move tyrquake-w.* 1
move universal-w.* 1
move uzebox-w.* 1
move vanillara-w.* 1
move vanillatd-w.* 1
move vaporspec-w.* 1
move vc4000-w.* 1
move vcmi-w.* 1
move vectrex-w.* 1
move vemulator-w.* 1
move vgmplay-w.* 1
move videopacplus-w.* 1
move virtualboy-w.* 1
move vis-w.* 1
move visco-w.* 1
move voidsw-w.* 1
move vpinball-w.* 1
move vsmile-w.* 1
move wasm4-w.* 1
move wii-w.* 1
move wiiu-w.* 1
move wiiware-w.* 1
move windows-w.* 1
move windows_installers-w.* 1
move witchaven-w.* 1
move wonderswan-w.* 1
move wonderswancolor-w.* 1
move wswan-w.* 1
move wswanc-w.* 1
move x1-w.* 1
move x68000-w.* 1
move xash3d_fwgs-w.* 1
move xbox-w.* 1
move xbox360-w.* 1
move xboxcloud-w.* 1
move xegs-w.* 1
move xrick-w.* 1
move yquake2-w.* 1
move zc210-w.* 1
move zeldac-w.* 1
move zmachine-w.* 1
move zx81-w.* 1
move zxspectrum-w.* 1
